# Use an official Node runtime as the base image
FROM node:16-alpine as development

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in package.json
RUN npm install

# Make sure the code inside the container is synced with your local code
RUN npm link ../react-scripts

# Start the development server
CMD ["npm", "start"]